CustomerManagement/Models/Branch.cs
using System.ComponentModel.DataAnnotations;

namespace CustomerManagement.Models
{
    public class Branch
    {
        [Key] public int BranchId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
    }
}

CustomerManagement/Models/ErrorViewModel.cs
namespace CustomerManagement.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CustomerManagement/Controllers/BranchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CustomerManagement.Data;
using CustomerManagement.Models;

namespace CustomerManagement.Controllers
{
    public class BranchesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BranchesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Branches
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var _Branch = await _context.Branches.ToListAsync();
            if (_Branch.Count < 1)
                await CreateTestData();

            return _context.Branches != null ?
                        View(await _context.Branches.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Branch'  is null.");
        }

        // GET: Branches/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Branches == null)
            {
                return NotFound();
            }

            var branch = await _context.Branches
                .FirstOrDefaultAsync(m => m.BranchId == id);
            if (branch == null)
            {
                return NotFound();
            }

            return View(branch);
        }

        // GET: Branches/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Branches == null)
            {
                return NotFound();
            }

            var branch = await _context.Branches.FindAsync(id);
            if (branch == null)
            {
                return NotFound();
            }
            return View(branch);
        }

        // PUT: Branches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BranchId,Name,Address,City,State,Zipcode")] Branch branch)
        {
            if (id != branch.BranchId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(branch);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BranchExists(branch.BranchId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(branch);
        }

        // GET: Branches/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Branches/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BranchId,Name,Address,City,State,Zipcode")] Branch branch)
        {
            if (ModelState.IsValid)
            {
                _context.Add(branch);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(branch);
        }

        // DELETE: Branches/5
        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
            try
            {
                var _Branches = await _context.Branches.FindAsync(id);

                if (_Branches != null)
                {
                    _context.Branches.Remove(_Branches);
                }
                await _context.SaveChangesAsync();
                return new JsonResult(_Branches);
            }
            catch (Exception)
            {
                throw;
            }
        }

        private bool BranchExists(int id)
        {
            return (_context.Branches?.Any(e => e.BranchId == id)).GetValueOrDefault();
        }
        private async Task CreateTestData()
        {
            foreach (var item in GetBranchList())
            {
                _context.Branches.Add(item);
                await _context.SaveChangesAsync();
            }
        }

        private IEnumerable<Branch> GetBranchList()
        {
            return new List<Branch>
            {
                new Branch {Name = "Branch 1", Address = "Nguy Nhu - Kon Tum", City = "Ha Noi", State = "Active", Zipcode = "001"},
                new Branch {Name = "Branch 2", Address = "1 - Vo Van Ngan", City = "Ho Chi Minh", State = "Active", Zipcode = "002"},
                new Branch {Name = "Branch 3", Address = "1 - Le Van Viet", City = "Ho Chi Minh", State = "Active", Zipcode = "003"},
                new Branch {Name = "Branch 4", Address = "1 - Le Van Chi", City = "Ho Chi Minh", State = "DeActive", Zipcode = "004"},
                new Branch {Name = "Branch 5", Address = "1 - Dinh Phong Phu", City = "Ho Chi Minh", State = "Active", Zipcode = "005"},
            };
        }
    }
}

CustomerManagement/Views/Branches/Create.cshtml
@model CustomerManagement.Models.Branch

@{
    ViewData["Title"] = "Create";
}

<h4>Create: Branch</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group row">
                <label asp-for="Name" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="Name" class="form-control" id="Name" type="text" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Address" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="Address" class="form-control" id="Address" type="text" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="City" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="City" class="form-control" id="City" type="text" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="State" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="State" class="form-control" id="State" type="text" />
                    <span asp-validation-for="State" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Zipcode" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="Zipcode" class="form-control" id="Zipcode" type="text" />
                    <span asp-validation-for="Zipcode" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

CustomerManagement/Views/Branches/Details.cshtml
@model CustomerManagement.Models.Branch

@{
    ViewData["Title"] = "Details";
}

<div class="col-md-8">
    <h4>Details: Branch</h4>
    <hr />
    <table class="BlueGreen">
    <tr><th>Id</th><td>@Model.BranchId</td></tr>
    <tr><th>Name</th><td>@Model.Name</td></tr>
    <tr><th>Address</th><td>@Model.Address</td></tr>
    <tr><th>City</th><td>@Model.City</td></tr>
    <tr><th>State</th><td>@Model.State</td></tr>
    <tr><th>Zipcode</th><td>@Model.Zipcode</td></tr>
</table>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.BranchId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CustomerManagement/Views/Branches/Edit.cshtml
@model CustomerManagement.Models.Branch

@{
    ViewData["Title"] = "Edit";
}

<h4>Edit: Branch</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BranchId" />
            
            <div class="form-group row">
                <label asp-for="Name" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="Name" class="form-control" id="Name" type="text" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Address" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="Address" class="form-control" id="Address" type="text" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="City" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="City" class="form-control" id="City" type="text" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="State" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="State" class="form-control" id="State" type="text" />
                    <span asp-validation-for="State" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Zipcode" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="Zipcode" class="form-control" id="Zipcode" type="text" />
                    <span asp-validation-for="Zipcode" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input type="submit" value="Edit" class="btn btn-primary" />
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CustomerManagement/Views/Branches/Index.cshtml
    @model IEnumerable<CustomerManagement.Models.Branch>

    @{
        ViewData["Title"] = "Index";
    }


    <h1 style="color: black; text-align: center;">CUSTOMER MANAGEMENT</h1>
    <hr />
    <p>
        <a class="btn btn-sm btn-danger" asp-action="Create">Add New</a>
    </p>
    <table id="tblBranches" class="BlueGreen" border="1">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.BranchId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.City)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.State)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Zipcode)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.BranchId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.State)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Zipcode)
                    </td>
                    <td>
                        <a class="btn btn-sm btn-success" asp-action="Edit" asp-route-id="@item.BranchId">Edit</a> |
                        <a class="btn btn-sm btn-info" asp-action="Details" asp-route-id="@item.BranchId">Details</a> |
                        <a class="btn btn-sm btn-danger" onclick="DeleteBranch('@item.BranchId')">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>


    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>


    <script>
        var DeleteBranch = function (id) {
            Swal.fire({
                title: 'Do you want to delete this item?',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        type: "POST",
                        url: "Branches/Delete?id=" + id,
                        success: function (result) {
                            console.log(result);
                            var message = "Branches has been deleted successfully. Branches ID: " + result.id;
                            Swal.fire({
                                title: message,
                                icon: 'info',
                                onAfterClose: () => {
                                    location.reload();
                                }
                            });
                        }
                    });
                }
            });
        };
    </script>

CustomerManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CustomerManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CustomerManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Branches" asp-action="Index">CustomerManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Branches" asp-action="Index">Branches</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CustomerManagement -
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>